project_id = "qldjhlnsphlixmzzrdwi"

[functions.sequence-wallet-manager]
verify_jwt = true

[functions.create-wallet]
verify_jwt = false

[functions.fix-missing-wallets]
verify_jwt = false

[functions.security-headers]
verify_jwt = false

[functions.delete-account]
verify_jwt = true

[functions.external-api]
verify_jwt = false

[functions.create-test-api-key]
verify_jwt = true

[functions.vault-club-user-creation]
verify_jwt = false

[functions.vault-club-auth-sync]
verify_jwt = false

[functions.vault-club-user-sync]
verify_jwt = false

[functions.vault-create]
verify_jwt = true

[functions.vault-join]
verify_jwt = true

[functions.vault-balance]
verify_jwt = true

[functions.vault-deposit]
verify_jwt = true

[functions.vault-harvest]
verify_jwt = true